[package]
name = "codegraide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
codegraide-core = { path = "../core" }
codegraide-analyzer-python = { path = "../analyzers/python" }
codegraide-analyzer-cpp = { path = "../analyzers/cpp" }
clap.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
tempfile = "3.27.0"
